# Generated by Django 3.2.8 on 2023-12-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='marks_obtained',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='maximum_marks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='minimum_marks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
